services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '3000:3000'
    environment:
        MONGODB_URI: mongodb://root:example@mongodb:27017/online-courses-platform?authSource=admin
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local
