services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    env_file:
      - mongodb.env
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    env_file:
      - redis.env
    volumes:
      - redis-data:/data

  neo4j:
    image: neo4j:5.9.0
    container_name: neo4j
    ports:
      - '7474:7474'  # HTTP
      - '7687:7687'  # Bolt
    env_file:
      - neo4j.env
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '3000:3000'
    env_file:
      - backend.env
    depends_on:
      - mongodb
      - redis
      - neo4j

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local
  neo4j-data:
    driver: local
  neo4j-logs:
    driver: local
